course = "mooc-java-programming-ii"

[exercises."part10-Part10_01.AverageOfNumbers"]
id = 87721
checksum = "4cdf257cea2388956d99983f5f02760d"

[exercises."part10-Part10_02.AverageOfSelectedNumbers"]
id = 87722
checksum = "d45538874c11be08803f983df130bdb7"

[exercises."part10-Part10_03.PositiveNumbers"]
id = 87723
checksum = "ac46021317ed4d952cdd8b2e8609463e"

[exercises."part10-Part10_04.Divisible"]
id = 87724
checksum = "40a9a7e9e8959390d82900c9c67654e1"

[exercises."part10-Part10_05.PrintingUserInput"]
id = 87725
checksum = "ee9c045a0231fac9adf0a675b97bbec1"

[exercises."part10-Part10_06.LimitedNumbers"]
id = 87726
checksum = "3bc84d53e374216555e61b9fe2c6ab18"

[exercises."part10-Part10_07.UniqueLastNames"]
id = 87727
checksum = "c44237795db45c4265b0411136ac3017"

[exercises."part10-Part10_08.Weighting"]
id = 87728
checksum = "9897d578f034c2f9468f342786e7e40f"

[exercises."part10-Part10_09.ReadingFilesPerLine"]
id = 87729
checksum = "13ded15e76f2dcd1255f1604d939f16a"

[exercises."part10-Part10_10.BooksFromFile"]
id = 87730
checksum = "7ea976300e2f71a5cd861a052a639b76"

[exercises."part10-Part10_11.WageOrder"]
id = 87731
checksum = "ea9105e5f2ecb30d508c6f7ef84e1e41"

[exercises."part10-Part10_12.StudentsOnAlphabeticalOrder"]
id = 87732
checksum = "8f7b561d7d7a1168fa52ea86969269f0"

[exercises."part10-Part10_13.LiteracyComparison"]
id = 87733
checksum = "15973313c58a0a868631db439b35760a"

[exercises."part10-Part10_14.Literature"]
id = 87734
checksum = "88d15046b3988c88eef3636f823ecdf8"

[exercises."part10-Part10_15.RegularExpressions"]
id = 87735
checksum = "11cfe652ab6cc1155a66701c0e66aa47"

[exercises."part10-Part10_16.EnumAndIterator"]
id = 87736
checksum = "6593623f1328656dda405073d5070d6b"

[exercises."part10-Part10_17.SortThemCards"]
id = 87737
checksum = "6301cfe4dc2ad2348130b131e4f913a1"

[exercises."part11-Part11_01.Customer"]
id = 87738
checksum = "aae56493ee5226e4a760bdcfea5fd658"

[exercises."part11-Part11_02.ABookAndAPlane"]
id = 87739
checksum = "a6497e6628fa0219c718ee893d282dd1"

[exercises."part11-Part11_03.ShowAndTicket"]
id = 87740
checksum = "a796a368861889d060ea3b1e69c1c058"

[exercises."part11-Part11_04.StudentAndUniversity"]
id = 87741
checksum = "6e76bdab2095be8d02a1b603c54061df"

[exercises."part11-Part11_05.ThePlayerAndTheBot"]
id = 87742
checksum = "efd1177efee4cfc9a4ca6c665f0858ee"

[exercises."part11-Part11_06.SaveablePerson"]
id = 87743
checksum = "6be4be28d0bcd3e4c10e6fa8e9888e40"

[exercises."part11-Part11_07.BiggerClassDiagram"]
id = 87744
checksum = "8285b18d1110c94fae521aebaf9a5828"

[exercises."part11-Part11_08.FirstPackages"]
id = 87745
checksum = "7d45f54869c8c5d19a39459e0a7677cc"

[exercises."part11-Part11_09.TheThreePackages"]
id = 87746
checksum = "80dacf2798bbc4ca663bb53a3329ead1"

[exercises."part11-Part11_10.FlightControl"]
id = 87747
checksum = "2c9c2067f1f3e9f7c1eea46e8936bddf"

[exercises."part11-Part11_11.ValidatingParameters"]
id = 87748
checksum = "59de4473d46a5d3983553a12f7d11fba"

[exercises."part11-Part11_12.SensorsAndTemperature"]
id = 87749
checksum = "3d99c815b692e1ef313e022c08f86ecc"

[exercises."part11-Part11_13.SaveableDictionary"]
id = 87750
checksum = "b269adc6891e3bfecf661bc878856a99"

[exercises."part12-Part12_01.Hideout"]
id = 87751
checksum = "956c8df982aec6b035b78d9e0d68cc64"

[exercises."part12-Part12_02.Pipe"]
id = 87752
checksum = "42d5ed1311396cfd17c0b2960903a451"

[exercises."part12-Part12_03.SumTheseForMe"]
id = 87753
checksum = "712ad1089f0bf55557f856b1e543e5ec"

[exercises."part12-Part12_04.List"]
id = 87754
checksum = "684050b9a3b6a25a72afd4b818c6f902"

[exercises."part12-Part12_05.HashMap"]
id = 87755
checksum = "83810010e064e23a1c42c1ff9cdaf7cf"

[exercises."part12-Part12_06.Numbers"]
id = 87756
checksum = "5e66fe0dce9f2edf8385b59877936fd6"

[exercises."part12-Part12_07.Die"]
id = 87757
checksum = "3b90f1281da49db45583025c3cccae62"

[exercises."part12-Part12_08.Lottery"]
id = 87758
checksum = "208b91e372fac123e81c8ab7aa806ec8"

[exercises."part12-Part12_09.ArrayAsAString"]
id = 87759
checksum = "54d7b9de1bc310bd429f956fcf6b5c3f"

[exercises."part12-Part12_10.MagicSquare"]
id = 87760
checksum = "1c8ad818e0a2abb14e1d5a4d6578e247"

[exercises."part13-Part13_01.MyFirstApplication"]
id = 87761
checksum = "caf2a48398ee15164650f3401adc701b"

[exercises."part13-Part13_02.ButtonAndLabel"]
id = 87762
checksum = "944689f177e8d505b07f980ab8a77c21"

[exercises."part13-Part13_03.ButtonAndTextField"]
id = 87763
checksum = "ceb75d06713edf5a67d96038015b76a9"

[exercises."part13-Part13_04.BorderPane"]
id = 87764
checksum = "6d6304722e56e98dcacfd215da45e25e"

[exercises."part13-Part13_05.TextStatistics"]
id = 87765
checksum = "1c31ed4b87f1e9bd05d7ac44f268aee4"

[exercises."part13-Part13_06.Notifier"]
id = 87766
checksum = "c6871425af4f89b33f2c88619ff66506"

[exercises."part13-Part13_07.TextStatisticsPart2"]
id = 87767
checksum = "b3c4e341132d29d0246799d368d1315d"

[exercises."part13-Part13_08.UserTitle"]
id = 87768
checksum = "02312023d087f678c8e8be610f3ce76a"

[exercises."part13-Part13_09.MultipleViews"]
id = 87769
checksum = "6e7343f8f3c399c92fd4cd602bcfca81"

[exercises."part13-Part13_10.Greeter"]
id = 87770
checksum = "f763047da18a7a0db06539abde788eb9"

[exercises."part13-Part13_11.Joke"]
id = 87771
checksum = "ecaeb762876099f84acc627802dca396"

[exercises."part13-Part13_12.VocabularyPractice"]
id = 87772
checksum = "d80774b9afa8126b8a1ff24a24726edf"

[exercises."part13-Part13_13.TicTacToe"]
id = 87773
checksum = "1f33f07a84c8098ced51667c3e7b6c86"

[exercises."part14-Part14_01.Shanghai"]
id = 87774
checksum = "329c60c77ed03a66bb36413ec1445cdb"

[exercises."part14-Part14_02.FinnishParties"]
id = 87775
checksum = "91287462b26a63a1a6d0db4885f8e9b1"

[exercises."part14-Part14_03.SavingsCalculator"]
id = 87776
checksum = "108dad184195bce0c445bfa40f3cf56a"

[exercises."part14-Part14_04.UnfairAdvertisement"]
id = 87777
checksum = "94a0a204bce235398bb1be8c6802848a"

[exercises."part14-Part14_05.CyclingStatistics"]
id = 87778
checksum = "f5232985975fd535f8361cf90641e9a1"

[exercises."part14-Part14_06.Smiley"]
id = 87779
checksum = "3c450f157ea97a6e94bdb12105e101dd"

[exercises."part14-Part14_07.Collage"]
id = 87780
checksum = "a7ba1a85a963e972bc4f005f23af386d"

[exercises."part14-Part14_08.Hurray"]
id = 87781
checksum = "aee737f9d25ba0365efbb2af1bd1ec23"

[exercises."part14-Part14_09.Asteroids"]
id = 87782
checksum = "c5701d88033d100854f17c2a43b1d986"

[exercises."part14-Part14_10.Database"]
id = 87783
checksum = "c2224ecde9cd7bf1933de0961474dda7"
